### ISSUE TITLE
Hello PCJ-blast team

### ISSUE THREAD

**Issue by jianshu93** [hpdcj/PCJ-blast#1]
Hello PCJ-blast team,

How do I obtain the PJC-blast.jar? How to compile/install et.al.?

Thanks,

Jianshu

**Comment by faramir** [comment]
Hello @jianshu93, I have just built the current release of PCJ-blast. It is available from [release page](https://github.com/hpdcj/PCJ-blast/releases/).

For the notes:
> To compile PCJ-blast Gradle Build Tool is required - it is available as `gradlew` or `gradlew.bat` file.
> 
> To build just execute: `./gradlew build` command
> To create fatjar execute: `./gradlew makeFatJar` command
